rename

diff --git a/cs300-run-docker b/cs300-run-docker
--- a/cs300-run-docker
+++ b/cs300-run-docker
@@ -1,9 +1,9 @@
 #! /bin/bash
 
 maindir=""
-destdir=cs300
-container_name=cs300-container
-network_name=cs300-network
+destdir=weijiew
+container_name=weijiew-container
+network_name=weijiew-network
 
 clean=false
 verbose=false
@@ -22,7 +22,7 @@ while test "$#" -ne 0; do
             platform=linux/arm64
             shift
         else
-            echo "\`cs300-run-docker --arm\` only works on ARM64 hosts" 1>&2
+            echo "\`weijiew-run-docker --arm\` only works on ARM64 hosts" 1>&2
             exit 1
         fi
     elif test "$1" = "-x" -o "$1" = "--x86-64" -o "$1" = "--x86_64" -o "$1" = "--amd64"; then
@@ -32,7 +32,7 @@ while test "$#" -ne 0; do
         if test "$arch" = "arm64" -o "$arch" = "aarch64"; then
             armtext=" [-a|--arm] [-x|--x86-64]"
         fi
-        echo "Usage: cs300-run-docker [-C|--clean]$armtext [-V|--verbose]" 1>&2
+        echo "Usage: weijiew-run-docker [-C|--clean]$armtext [-V|--verbose]" 1>&2
         exit 1
     fi
 done
@@ -43,9 +43,9 @@ elif test -z "$platform"; then
     platform=linux/amd64
 fi
 if test -z "$tag" -a "$platform" = linux/arm64; then
-    tag=cs300:arm64
+    tag=weijiew:arm64
 elif test -z "$tag"; then
-    tag=cs300:latest
+    tag=weijiew:latest
 fi
 
 vexec () {
@@ -64,13 +64,13 @@ has_container() {
 }
 
 create_network() {
-    echo "cs300 network not found, creating one..."
-    docker network create -d bridge cs300-network
+    echo "weijiew network not found, creating one..."
+    docker network create -d bridge weijiew-network
 }
 
 remove_containers() {
-    echo "Removing all existing cs300 containers..."
-    docker ps -a -f name=cs300 --format "{{.ID}}" | while read line ; do docker rm --force $line ; done
+    echo "Removing all existing weijiew containers..."
+    docker ps -a -f name=weijiew --format "{{.ID}}" | while read line ; do docker rm --force $line ; done
 }
 
 start_container() {
@@ -86,8 +86,8 @@ start_new_container() {
         --platform $platform \
         --privileged \
         --cap-add=SYS_PTRACE --cap-add=NET_ADMIN --security-opt seccomp=unconfined \
-        -v "$maindir/home":/home/cs300-user \
-        -w "/home/cs300-user" \
+        -v "$maindir/home":/home/weijiew-user \
+        -w "/home/weijiew-user" \
         -p "0.0.0.0:9095:9095" \
         --network "$network_name" \
         $netarg$sshenvarg $tag
@@ -103,7 +103,7 @@ myfileid=`stat $statformatarg %d:%i "${BASH_SOURCE[0]}" 2>/dev/null`
 dir="`pwd`"
 subdir=""
 while test "$dir" != / -a "$dir" != ""; do
-    thisfileid=`stat $statformatarg %d:%i "$dir"/cs300-run-docker 2>/dev/null`
+    thisfileid=`stat $statformatarg %d:%i "$dir"/weijiew-run-docker 2>/dev/null`
     if test -n "$thisfileid" -a "$thisfileid" = "$myfileid"; then
         maindir="$dir"
         break
@@ -131,7 +131,7 @@ if test -n "$maindir"; then
         image="`echo $existing_image | sed 's/^.*,//'`"
         image12="`echo $image | head -c 12`"
         echo "* Using running container $image12, created $created_at" 1>&2
-        echo "- To start a new container, exit then \`cs300-run-docker -f\`" 1>&2
+        echo "- To start a new container, exit then \`weijiew-run-docker -f\`" 1>&2
         echo "- To kill this container, exit then \`docker kill $image12\`" 1>&2
         vexec docker exec -it$sshenvarg $image /bin/bash
     fi
